
export const ACTION_FETCH = 'ACTION_FETCH';
export const ACTION_FOO = 'ACTION_FOO';
export const ACTION_ADD_TO_DO = 'ACTION_ADD_TO_DO';
export const ACTION_GET_PM_ARTICLE_LIST = 'ACTION_GET_PM_ARTICLE_LIST';
export const ACTION_PM_ACTIVE_NEWS = 'ACTION_PM_ACTIVE_NEWS'
export const ACTION_UPDATE_LOCATION = 'ACTION_UPDATE_LOCATION'
export const ACTION_UPDATE_WEATHER = 'ACTION_UPDATE_WEATHER'