
export const GET_PRODUCT_LIST_SUCC = 'GET_PRODUCT_LIST_SUCC'

export const CHANGE_PRODUCT_LIST_REFRESHING = 'CHANGE_PRODUCT_LIST_REFRESHING'

export const CHANGE_PRODUCT_LIST_LOADINGMORE = 'CHANGE_PRODUCT_LIST_LOADINGMORE'

export const TABBAR_SHOULD_SHOW = 'TABBAR_SHOULD_SHOW'

export const GET_VIEW_RECORDS = 'GET_VIEW_RECORDS'